Implement the basics of a Windows-friendlier environment for builds, micromvn: fix testing on Windows
Fact is, in practice, this means figuring out how to patch over the stuff Windows doesn't have.

Being able to rely on gabien-ready for setup should allow mitigations of the worst stuff though.

diff --git a/bin/gabien-ready b/bin/gabien-ready
--- a/bin/gabien-ready
+++ b/bin/gabien-ready
@@ -4,17 +4,18 @@
 # To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
 # A copy of the Unlicense should have been supplied as COPYING.txt in this repository. Alternatively, you can find it at <https://unlicense.org/>.
 
-# Shell script common functions.
+# Ensures gabien-common is ready for use in a release.
+# Be sure to set GABIEN_NATIVES_DEV=1 to unlock the natives test for dev releases.
 
-if [ ! -e "$JAVA_HOME_GABIEN" ]; then
- echo "JAVA_HOME_GABIEN (JDK for use with GaBIEn) not set or doesn't exist."
- echo "Value: $JAVA_HOME_GABIEN"
- echo "Example: /usr/lib/jvm/java-17-openjdk-amd64"
+set -e
+
+if [ ! -e "$JAVA_1_8_HOME" ]; then
+ echo "gabien-ready: Activation was likely unsuccessful in providing a Java 1.8 environment. Aborting."
  exit 1
 fi
 
-if [ "$GABIEN_SHELL_COMMON_DID_JHOOK" = "" ]; then
- export JAVA_HOME="$JAVA_HOME_GABIEN"
- export PATH="$JAVA_HOME_GABIEN/bin:$PATH"
- export GABIEN_SHELL_COMMON_DID_JHOOK=1
-fi
+cd "$GABIEN_HOME"
+
+umvn test -q
+umvn package-only -q
+umvn install-only -q
